---
- name: Enable nginx repo.
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  when: nginx_yum_repo_enabled | bool

- name: Ensure nginx is installed.
  package:
    name: "{{ nginx_package_name }}"
    state: present

- name: Ensure nginx modules is installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nginx_package_modules }}"
